// vue-app/src/components/AddVideo.vue
<template>
	<form @submit="onSubmit" class="add-form">
    <div class="form-control">
      <label>Search Video</label>
      <input type="title" v-model="title" name="title" placeholder="Search" />
    </div>
    <input type="submit" value="Add Video" class="btn btn-block" />
  </form>
</template>

<script>
export default {
	name: 'AddVideo',
	data() {
		return {
			title: ''
		}
	},
	methods: {
		onSubmit(e) {
			e.preventDefault();
			
			if (this.title) {

				this.$emit('add-video', this.title)
				this.title = ''
			}
		}
	}
} 
</script>

// react-app/src/components/AddVideo.js
import { useState } from "react"

export const AddVideo = ({ onAdd }) => {
	const [Title, setTitle] = useState('')

	const onSubmit = (e) => {
		e.preventDefault()
		
		if(Title) {
			onAdd({ Title })
		}
	}

	return (
		<form className='add-form' onSubmit={onSubmit}>
			<div className='form-control'>
				<label>Search Video:</label>
				<input type='text' placeholder='Search' value={Title} onChange={(e) => setTitle(e.target.value)}/>
			</div>
			<input type='submit' className='btn btn-block' value='Add video' />
		</form>
	)
}

export default AddVideo
