// vue-app/src/components/AddVideo.vue
<template>
	<form @submit="onSubmit" class="add-form">
    <div class="form-control">
      <label>Search Video</label>
      <input type="title" v-model="title" name="title" placeholder="Search" />
    </div>
    <input type="submit" value="Add Video" class="btn btn-block" />
  </form>
</template>

<script>
export default {
	name: 'AddVideo',
	data() {
		return {
			title: ''
		}
	},
	methods: {
		onSubmit(e) {
			e.preventDefault();
			
			if (this.title) {

				this.$emit('add-video', this.title)
				this.title = ''
			}
		}
	}
} 
</script>

// angular-app/src/app/components/add-video/add-video.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { Video } from 'src/app/Video';

@Component({
  selector: 'app-add-video',
  templateUrl: './add-video.component.html',
  styleUrls: ['./add-video.component.css']
})
export class AddVideoComponent implements OnInit {
  @Output() onAddVideo: EventEmitter<string> = new EventEmitter();
  title: string;

  constructor() { }

  ngOnInit(): void {
  }

  onSubmit() {
    if (this.title) {
      this.onAddVideo.emit(this.title);

      this.title = '';
    }
  }

}

<form class="add-form" (ngSubmit)="onSubmit()">
	<div class="form-control">
		<label for="title">Search Video</label>
		<input type="text" name="title" id="title" placeholder="Search" [(ngModel)]="title">
		<input type="submit" value="Add Video" class="btn btn-block">
	</div>
</form>
